font-family = ""
font-family = Hack Nerd Font Mono
font-family-bold = ""
font-family-bold = Hack
font-family-bold = Hack Nerd Font Mono
font-family-italic = ""
font-family-italic = Hack Nerd Font Mono
font-family-bold-italic = ""
font-family-bold-italic = Hack
font-family-bold-italic = Hack Nerd Font Mono
font-style = Regular
font-style-bold = Medium
font-style-italic = Italic
font-style-bold-italic = Medium Italic
