- name: Install aws-vault
  when: ansible_os_family == "Darwin"
  community.general.homebrew_cask:
    name: aws-vault
    state: latest

- name: Install aws-vault
  when: ansible_os_family == "Debian"
  community.general.homebrew:
    name: aws-vault
    state: latest
