---
- name: Install Docker
  when: ansible_os_family == "Darwin"
  community.general.homebrew_cask:
    name: docker
    state: present
    accept_external_apps: true

- name: Update apt cache
  when: ansible_os_family == "Debian"
  become: yes
  apt:
    update_cache: yes

- name: Install required dependencies
  when: ansible_os_family == "Debian"
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: present

- name: Add Docker's official GPG key
  when: ansible_os_family == "Debian"
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Install Docker (Linux)
  when: ansible_os_family == "Debian"
  become: yes
  ansible.builtin.shell: >
    sudo rm /etc/apt/sources.list.d/docker.list
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt update

# - name: Add Docker's official APT repository
#   when: ansible_os_family == "Debian"
#   become: yes
#   apt_repository:
#     repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
#     state: present

- name: Install Docker CE
  when: ansible_os_family == "Debian"
  become: yes
  apt:
    name:
      - docker-ce
      - containerd.io
    # state: present

- name: Ensure Docker service is running
  when: ansible_os_family == "Debian"
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

