- name: Postman
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: "[Non-WSL] Install Postman"
      become: yes
      unarchive:
        src: https://dl.pstmn.io/download/latest/linux64
        dest: /opt
        remote_src: yes
        creates: /opt/Postman/Postman
      when: not is_wsl

    - name: "[Non-WSL] Ensure local applications folder exists"
      become: yes
      file:
        path: /usr/local/share/applications
        state: directory
      when: not is_wsl

    - name: "[Non-WSL] Add Postman desktop file"
      become: yes
      copy:
        src: postman.desktop
        dest: /usr/local/share/applications/postman.desktop
      when: not is_wsl
