#!/bin/bash

# Log dotfiles setup
exec > >(tee -i $HOME/log/dotfiles_install.log)
exec 2>&1

## detect OS
case $(uname -s) in
  Darwin)
    OS_MAC=1 
    ;;

  Linux)
    OS_LINUX=1
    ;;

  *)
    echo "Unknown operating system."
	exit 1
	;;
esac

## detect architecture
case $(uname -m) in
  arm64)
    ARCH_ARM=1 
    ;;

  x86_64)
    ARCH_X86=1
    ;;

  *)
    echo "Unknown architecture."
	exit 1
	;;
esac

## Install Xcode tools

if [ -n "$OS_MAC" ]; then
		if [ -z "$(xcode-select -p)" ]; then
				echo "INFO: Install developer tools."

				xcode-select --install
		fi
fi

## Install Brew

echo "INFO: Install brew."

if [ -n "$OS_MAC" ]; then
		echo "INFO: Install brew on MacOS."

		if [ -z "$(which brew)" ]; then
				/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

				if [ -n "$ARCH_ARM" ]; then
						echo "INFO: Invoke brew shellenv (M1)."

						eval "$(/opt/homebrew/bin/brew shellenv)"
				elif [ -n "$ARCH_X86" ]; then 
						echo "INFO: Invoke brew shellenv (Intel)."

						eval "$(/usr/local/homebrew/bin/brew shellenv)"
				fi
		fi
fi

if [ -n "$OS_LINUX" ]; then
		echo "INFO: Install linuxbrew on Linux."

		if [ -z "$(which brew)" ]; then
				echo "INFO: Install brew."

				/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
				eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

				sudo apt install build-essential
		fi

		if [ -z "$(which gcc)" ]; then
				echo "INFO: (brew) Install gcc."

				brew install gcc
		fi
fi


