#!/bin/bash

# Log dotfiles setup
mkdir $HOME/log
exec > >(tee -i $HOME/log/dotfiles_setup.log)
exec 2>&1

set -x

## Run ansible for all playbooks

if [ -n "$(which ansible-galaxy)" ]; then
		ansible-galaxy collection install community.general
fi

## Run ansible for all playbooks

if [ -n "$(which ansible-playbook)" ]; then
		echo "INFO: Running all playbooks."
		ansible-playbook -K playbooks/_all.yaml
fi
