#!/bin/bash
set -euo pipefail

if [ -z "${DOTFILES_DIR:-}" ]; then
    DOTFILES_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
fi

# ===============================
# Install brew
# ===============================

echo "INFO: Install linuxbrew on Linux."
if [ -z "$(which brew)" ]; then
        echo "INFO: Install brew."

        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

        sudo apt update 
        sudo apt install build-essential -y
fi

if [ -z "$(which gcc)" ]; then
        echo "INFO: (brew) Install gcc."

        brew install gcc
fi

# ===============================
# Homebrew Path Configuration
# ===============================

echo "Configuring Homebrew path for linuxbrew."
export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
export HOMEBREW_CELLAR="$HOMEBREW_PREFIX/Cellar"

# ===============================
# Homebrew Environment Variables
# ===============================

ARCH_FILE="$HOME/.zsh_arch"

echo "Generating .zsh_arch based on system architecture..."
cat > "$ARCH_FILE" <<EOL

export HOMEBREW_PREFIX="$HOMEBREW_PREFIX"
export HOMEBREW_CELLAR="$HOMEBREW_CELLAR"
export PATH="$HOMEBREW_PREFIX/bin:$PATH"
EOL

echo ".zsh_arch successfully generated."

# ===============================
# Install Core Homebrew Dependencies
# ===============================

echo "Installing homebrew core deps..."
"$DOTFILES_DIR/script/brew-apply-manifest" base.core

echo "Successfully installed core packages."

if [ -z "${CLOUD:-}" ]; then
        # ===============================
        # Install 1Password via brew
        # ===============================
        
        echo "Installing homebrew 1pass deps..."
        "$DOTFILES_DIR/script/brew-apply-manifest" auth.1password

        echo "Successfully installed 1pass packages."

        # ===============================
        # Prompt to Login to 1Password and Enable SSH Agent
        # ===============================

        echo "Please log in to 1Password and enable the SSH Agent."
        echo "1Password > Sign-in > Preferences > Developer"
        read -p "After completing the above steps, press Enter to continue..."


        # ===============================
        # Link 1Password SSH Key
        # ===============================

        SSH_AUTH_SOCK="$HOME/.1password/agent.sock"
else
    echo "Installing cloud development manifests..."
    "$DOTFILES_DIR/script/brew-apply-manifest" dev.common infra.common
fi
