- name: Install languages via asdf
  hosts: 127.0.0.1
  connection: local

- import_playbook: ruby.yaml
- import_playbook: python.yaml
- import_playbook: nodejs.yaml
- import_playbook: golang.yaml

tasks:
  - name: Install asdf languages via .tool-versions
    ansible.builtin.shell: 
      chdir: ~
      cmd: asdf install
