- name: Install languages via asdf
  hosts: 127.0.0.1
  connection: local

- import_playbook: "{{ item }}"
  with_fileglob:
    - "./languages/*.yaml"

  tasks:
    - name: Install asdf languages via .tool-versions
      ansible.builtin.shell: 
        chdir: ~
        cmd: asdf install
