- name: Install languages via asdf
  hosts: 127.0.0.1
  connection: local

  tasks:
    - import_tasks: ruby.yaml
    - import_tasks: python.yaml
    - import_tasks: nodejs.yaml
    - import_tasks: golang.yaml
    - import_tasks: java.yaml

    - name: Install asdf languages via .tool-versions
      ansible.builtin.shell: 
        chdir: ~
        cmd: asdf install
