- name: Golang
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install Golang dependencies
      community.general.homebrew:
        name: coreutils
        state: latest

    - name: Add Golang asdf plugin
      ansible.builtin.shell: asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
