- name: Install Golang dependencies
  community.general.homebrew:
    name: coreutils
    state: latest

- name: Add Golang asdf plugin
  ansible.builtin.shell: 
    cmd: asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
    creates: ~/.asdf/plugins/golang/
