- name: Install NodeJS dependencies
  community.general.homebrew:
    name: node-build
    state: latest

- name: Add NodeJS asdf plugin
  ansible.builtin.shell: asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
