- name: Install macOS apps
  hosts: localhost

  tasks:
  - name: Install apps (macOS)
    when: ansible_os_family == "Darwin"
    community.general.homebrew_cask:
      name: "{{ item }}"
      state: present
      accept_external_apps: true
    loop:
      - discord
      - obsidian
      - signal
      - spotify
      - todoist
      - zoom
      - slack
      - gifcapture
      - tailscale

  - name: Install apps (Linux)
    when: ansible_os_family == "Debian"
    community.general.flatpak:
      name: "{{ item }}"
      state: present
    loop:
    - com.discordapp.Discord
    - md.obsidian.Obsidian
    - org.signal.Signal
    - com.spotify.Client
    - com.todoist.Todoist
    - us.zoom.Zoom
    - com.slack.Slack
