- name: Setup and ensure prerequisites
  hosts: localhost
  become: yes
  tasks:
    - name: Gather the OS type
      setup:
        filter: ansible_os_family

    - name: Ensure Flatpak is installed
      apt:
        name: flatpak
        state: present
      when: ansible_os_family == "Debian"

    - name: Add the Flathub repository
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      args:
        creates: "/var/lib/flatpak/repo/flathub.flatpakrepo"
      when: ansible_os_family == "Debian"

# Import the playbooks at the play level, not within a tasks block.
- import_playbook: core.yaml
- import_playbook: languages/core.yaml
- import_playbook: developer/core.yaml
- import_playbook: apps/core.yaml

