- name: Configure machine for development work
  hosts: 127.0.0.1
  connection: local

- import_playbook: core.yaml
- import_playbook: languages/core.yaml
- import_playbook: developer/core.yaml
- import_playbook: apps/core.yaml
