# TODO: Use async packages in many places to speed things up!
- name: Core OS packages
  hosts: 127.0.0.1
  connection: local

  vars:
    # distribution_fallback:
    #   'Pop!_OS': 'Ubuntu'
    # distribution: "{{ distribution_fallback[ansible_distribution] | default(ansible_distribution) }}"

  tasks:
    - name: Create home directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0700
      loop:
        - ~/.local
        - ~/.local/lib
        - ~/.local/bin
        - ~/.local/src
        - ~/.local/artifacts
        - ~/.config
        - ~/.git
        - ~/.ssh
        - ~/dev

    - name: Install 1password
      community.general.homebrew_cask: 
        name: 1password
        state: latest

    - name: Install 1password-cli
      community.general.homebrew_cask: 
        name: 1password-cli
        state: latest

    - name: Login to 1password and enable SSH Agent
      ansible.builtin.pause:
        prompt: "1Password > Sign-in > Preferences > Developer"

    - name: Unpack dotfiles 
      copy:
        src: "{{ item }}"
        dest: "~"
        mode: 0700
        directory_mode: yes
      with_fileglob:
      - "../.*"

    - name: Unpack dotfile directories
      copy:
        src: "../{{ item }}"
        dest: "~/{{ item }}"
        mode: 0700
        directory_mode: yes
      loop:
        - .config/
        - .git/
        - .local/
        - .ssh/

    # - name: Link amethyst preferences
    
    - name: Link 1password ssh key
      ansible.builtin.shell: mkdir -p ~/.1password && ln -sf ~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock ~/.1password/agent.sock

    - name: Update brew
      community.general.homebrew: 
        update_homebrew: true
        upgrade_all: true

     

    # - name: Add ~/.local/bin to PATH
    #   lineinfile:
    #     path: ~/.local/bin
    #     line: export PATH=$PATH:~/.local/bin

    # - name: Update APT package list
    #   become: yes
    #   apt:
    #     update_cache: yes
    #   register: apt_update
    #   retries: 5
    #   until: apt_update is success

    # - name: Upgrade to latest APT packages
    #   become: yes
    #   apt:
    #     upgrade: yes

    # - name: Install core packages
    #   become: yes
    #   apt:
    #     package: "{{ item }}"
    #   loop:
    #     - curl
    #     - dconf-editor
    #     - exfat-fuse
    #     - htop
    #     - inetutils-traceroute
    #     - jq
    #     - net-tools
    #     - p7zip-full
    #     - unzip
    #     - uuid
    #     - xclip

