- name: Core OS packages
  hosts: 127.0.0.1
  connection: local

  vars:
    # distribution_fallback:
    #   'Pop!_OS': 'Ubuntu'
    # distribution: "{{ distribution_fallback[ansible_distribution] | default(ansible_distribution) }}"
    # is_ubu_22_04_or_newer: "{{ distribution == 'Ubuntu' and (ansible_distribution_major_version | int) >= 22 }}"

  tasks:
    - name: Create home directories
      file:
        path: "{{ dir }}"
        state: directory
        mode: 0700
      loop:
        - ~/.local
        - ~/.local/lib
        - ~/.local/bin
        - ~/.local/src
        - ~/.local/artifacts
        - ~/.config
        - ~/dev

    - name: Unpack dotfiles 
      copy:
        src: "{{ item }}"
        dest: "~"
        mode: 0700
        directory_mode: yes
      with_fileglob:
      - "../.*"

    - name: Update brew
      community.general.homebrew: 
        update_homebrew: true
        upgrade_all: true
     
    # - name: Link amethyst preferences

    # - name: Add ~/.local/bin to PATH
    #   lineinfile:
    #     path: ~/.local/bin
    #     line: export PATH=$PATH:~/.local/bin

    # - name: Update APT package list
    #   become: yes
    #   apt:
    #     update_cache: yes
    #   register: apt_update
    #   retries: 5
    #   until: apt_update is success

    # - name: Upgrade to latest APT packages
    #   become: yes
    #   apt:
    #     upgrade: yes

    # - name: Install core packages
    #   become: yes
    #   apt:
    #     package: "{{ item }}"
    #   loop:
    #     - curl
    #     - dconf-editor
    #     - exfat-fuse
    #     - htop
    #     - inetutils-traceroute
    #     - jq
    #     - net-tools
    #     - p7zip-full
    #     - unzip
    #     - uuid
    #     - xclip

