# TODO: Use async packages in many places to speed things up!
- name: Core OS packages
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Create home directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0700
        owner: "{{ ansible_user_id }}"
      loop:
        - ~/.local
        - ~/.local/lib
        - ~/.local/bin
        - ~/.local/src
        - ~/.local/artifacts
        - ~/.config
        - ~/.git
        - ~/.ssh
        - ~/dev
        - ~/second-brain

    - name: Install 1password
      community.general.homebrew_cask: 
        name: 1password
        state: latest

    - name: Install 1password-cli
      community.general.homebrew_cask: 
        name: 1password-cli
        state: latest

    - name: Login to 1password and enable SSH Agent
      ansible.builtin.pause:
        prompt: "1Password > Sign-in > Preferences > Developer"

    - name: Unpack dotfiles 
      synchronize:
        src: "{{ item }}"
        dest: "~"
      with_fileglob:
      - "../.*"
      become: yes

    - name: Unpack dotfile directories
      synchronize:
        src: "../{{ item }}"
        dest: "~/{{ item }}"
      loop:
        - .config/
        - .git/
        - .local/
        - .ssh/
      become: yes

    - name: Update macOS defaults
      ansible.builtin.shell: source ~/.osx

    - name: Install (copy) amethyst preferences
      ansible.builtin.shell: cp ~/.config/amethyst/* ~/Library/Preferences/
    
    - name: Link 1password ssh key
      ansible.builtin.shell: mkdir -p ~/.1password && ln -sf ~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock ~/.1password/agent.sock

    - name: Accept new ssh fingerprints
      shell: ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts
      loop: 
        - github.com

    - name: Update brew
      community.general.homebrew: 
        update_homebrew: true
        upgrade_all: true

    - name: Install utilities
      community.general.homebrew:
        name: "{{ item }}"
        state: latest
      loop:
        - wget
        - marp-cli
        - ripgrep
        - fzf
        - tmux
        - tldr
        - asdf
        - awscli
        - fd
        - direnv
        - aws-sso-creds
        - coreutils
        - fd
        - gh
        - just
        - tldr3
        - jq
        - yq

    - name: Install zplug
      ansible.builtin.shell: 
        cmd: curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
        creates: ~/.zplug

