- name: Fonts
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Tap fonts
      community.general.homebrew_tap:
        name: homebrew/cask-fonts

    - name: Install fonts
      community.general.homebrew_cask:
        name: font-hack-nerd-font
        state: latest
